version: '2'

services:
  elasticsearch:
    build:
      context: ./alpine-elasticsearch
    command: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
volumes:
  es_data: {}
