version: '2'

services:
  config-editor:
    build:
      context: ./config-editor
      args:
        ES_UID: ${ES_UID}
        ES_USER: ${ES_USER}
        LS_UID: ${LS_UID}
        LS_USER: ${LS_USER}
        KB_UID: ${KB_UID}
        KB_USER: ${KB_USER}
    command: /bin/true
    volumes:
      - es_data:/volumes/elasticsearch/es_data
      - ls_config:/volumes/logstash/config
      - ls_confd:/volumes/logstash/conf.d
      - kb_config:/volumes/kibana/config
  elasticsearch:
    build:
      context: ./alpine-elasticsearch
    command: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
  logstash:
    build:
      context: ./alpine-logstash
      args:
        LS_VERSION: 5.0.0
        LS_HOME: /opt/logstash
        LS_USER: logstash
        LS_UID: ${LS_UID}
        LS_PLUGINS:
        LS_XMX: -Xmx256m
        LS_XMS: -Xms256m
    command: logstash
    links:
      - elasticsearch
    #ports:
    #  - "514:514/udp"
    volumes:
      - ls_confd:${LS_HOME}/conf.d
      - ls_config:${LS_HOME}/config
    #environment:
    #  LS_SETTINGS_DIR:
  kibana:
    build:
      context: ./alpine-kibana
      args:
        KB_VERSION: ${KB_VERSION}
        KB_HOME: ${KB_HOME}
        KB_USER: ${KB_USER}
        KB_UID: ${KB_UID}
        PLUGINS: ${KB_PLUGINS}
    command: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch
    volumes:
      - kb_config:${KB_CONF_MOUNT}
    environment:
      KB_SETTINGS_DIR: ${KB_CONF_MOUNT}
volumes:
  es_data: {}
  kb_config: {}
  ls_confd: {}
  ls_config: {}
